"""add_code_chunks_table

Revision ID: fdbb53631cb3
Revises: 9cf9a410f063
Create Date: 2026-05-17 11:51:18.670465

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdbb53631cb3'
down_revision: Union[str, Sequence[str], None] = '9cf9a410f063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector') 
    op.create_table('code_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('symbol_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('symbol_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'file_path', 'start_line', 'content_hash', name='uq_code_chunks_repo_path_start_hash')
    )
    op.create_index('ix_code_chunks_repo_file_lines', 'code_chunks', ['repository_id', 'file_path', 'start_line', 'end_line'], unique=False)
    op.create_index(op.f('ix_code_chunks_repository_id'), 'code_chunks', ['repository_id'], unique=False)
    op.drop_table('verification_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('verification_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('command', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('output', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('verification_results_agent_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_results_pkey'))
    )
    op.drop_index(op.f('ix_code_chunks_repository_id'), table_name='code_chunks')
    op.drop_index('ix_code_chunks_repo_file_lines', table_name='code_chunks')
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
